d = [   "Crack an egg over your head.",
        "Attempt to do 10 pushups.",
        "Eat a plate of (dinner, dessert, whatever) with no hands.",
        "Crabwalk across the room.",
        "Army crawl across the room.",
        "Stand on your hands.",
        "Fetch (item of choice in another room) with a blindfold on.",
        "Eat a spoonful of sugar.",
        "Eat a spoonful of hot sauce.",
        "Eat a hot pepper.",
        "Do your best Buzz Lightyear impression.",
        "Do your best Mickey Mouse impression.",
        "Do your best lion roar.",
        "Do your best Batman impression.",
        "Do your best Disney princess impression.",
        "Attempt a cartwheel.",
        "Make up a poem aloud.",
        "Dump a cup of ice water over your head.",
        "Prank call Grandma.",
        "Attempt to slip on a banana peel (or pretend to).",
        "Make a really silly face and take a selfie.",
        "Draw a picture of (you pick) while blindfolded.",
        "Take off your socks with a pair of tongs.",
        "Run around the outside of the house three times.",
        "Act like a cat.",
        "Act like a monkey.",
        "Chug a cup of (milk, water, juice, etc.).",
        "Touch your nose with your tongue.",
        "Juggle eggs (outside.)",
        "Stick a spoon on your nose and keep it there as long a possible.",
        "Sing the ABCs backward.",
        "Spin in circles for 10 seconds.",
        "Text someone using only your nose.",
        "Pop a balloon without using your hands or your teeth.",
        "Suck an ice cube until melted without chewing (or a couple of ice cubes at the same time if they are small).",
        "Hold an ice cube in your hand until it melts.",
        "Go outside and yell “Happy New Year!",
        "Eat a clove or a spoonful of minced garlic.",
        "Sniff the pepper shaker..",
        "Do your makeup in 10 seconds (eye shadow, blush, and lipstick).",
        "Sniff (choice person)’s shoe.",
        "Do the chicken dance.",
        "Do the macarena silently until it is your turn again.",
        "Go ask the neighbor for a cup of sugar.",
        "Wear your shoes on your hands for the next 5 minutes.",
        "Spin 10 times and try to do hopscotch.",
        "Spin 10 times and try to skip rope.",
        "Do the disco.",
        "Stuff as many marshmallows (or grapes, donut holes, etc.) into your mouth as you can!",
        "Use the driveway as a catwalk for five minutes, while giving the model wave to any passing cars or people.",
        "Wear underwear on your head for the rest of the game.",
        "Draw a mustache on yourself without a mirror.",
        "Switch clothes with someone.",
        "Try to dress the family pet.",
        "Stack five cookies on your forehead. (Oreos work great!)",
        "Do the Hokey Pokey without singing it.",
        "Go outside and yell “I pick my nose!” to the first person you see.",
        "Finish every sentence with the words “while I dance” or “with a cherry on top.” (Or whatever silly thing you can think of!)",
        "Belt out a song of choice.",
        "Let someone tickle you for 30 seconds.",
        "Let someone fix your hair the way they want and leave it that way.",
        "Have a full conversation with a broom.",
        "Sing what you have to say instead of talking.",
        "Try to catch three pieces of small food tossed by someone in your mouth (popcorn, grapes, etc.).",
        "Use a hairbrush as a microphone.",
        "Talk in the third person.",
        "Talk in a high-pitched voice.",
        "Be a commentator for the remainder of the game.",
        "Pretend to be T-Rex.",
        "Talk and act like a robot.",
        "Jump into the pool or submerge yourself in the bathtub fully clothed.",
        "Keep your finger on the tip of your nose as if it’s stuck there.",
        "Stop blinking for 30 seconds.",
        "Talk without moving your lips.",
        "Skip everywhere you go instead of walking or running.",
        "Start every sentence with “what is…”.",
        "Jump while holding a cup full of water above your head without spilling it.",
        "Remove one sock and shoe so that one foot is bare for the rest of the game.",
        "Take a bite of a sandwich made by everyone that contains whatever they desire, and try to guess each ingredient on the sandwich.",
        "Bob for an apple. (Large mixing bowl full of water works well!)",
        "Snort excessively when laughing.",
        "Pretend to have chicken pox by sticking round labels all over yourself.",
        "Talk and act like a cowboy or cowgirl.",
        "Get wrapped from head to toe in toilet paper.",
        "Make a face mask out of sliced cheese.",
        "Walk backwards wherever you go.",
        "Put all clothes on inside out.",
        "Put all clothes on backwards.",
        "Take your age, reverse the numbers, and act that age. (If player is only a single digit, just add a 0 to their age. Example: player is 8, so they must act 80.)",
        "Smell everyone’s breath and guess what they ate last.",
        "Talk with your tongue sticking out.",
        "Talk while holding your tongue with your index finger and thumb.",
        "Put your leg behind your head.",
        "Draw a stickman on paper by holding the writing utensil in your mouth.",
        "Go outside and howl at the moon. (If it’s dark outside).",
        "Do jumping jacks until your next turn.",
        "Do the cha cha until your next turn.",
        "Tie your shoes together and try not to forget!",
        "Hug your mailbox (or a tree or lawn ornament) for 20 seconds.",
        "Take a wet willy.",
        "Eat a huge spoonful of peanut butter and sing the ABCs.",
        "Play fetch like a dog, running on all fours and using only your mouth to fetch.",
        "Take a bite out of a stick of butter.",
        "Put ice cubes down your shirt, with shirt tucked in.",
        "Act like a chicken."
    ]
