t = [   "When was the last time you cleaned your room?",
        "Is there a mess under your bed?",
        "Is there a mess in your closet?",
        "Have you ever snuck a snack?",
        "Have you ever said you finished your dinner when you really didn’t?",
        "Have you ever cheated on a test?",
        "Do you have a crush on anyone?",
        "What would you do with $1,000?",
        "If you could be any celebrity, who would you be and why?",
        "Have you ever faked a sickness to stay home from school?",
        "Have you ever used your lunch money for something other than lunch?",
        "Have you ever watched a movie or TV show that you know you’re not allowed?",
        "What are some ways you cheat on chores?",
        "What is the least favorite gift you’ve ever received?",
        "Are you afraid of the dark?",
        "Do you have any secrets?",
        "Do you keep a diary/journal?",
        "Is there anything that you would change about yourself?",
        "What is your biggest fear?",
        "Have you ever skipped school?",
        "What is your worst habit?",
        "Have you ever lied about your age?",
        "Have you ever lied to me?",
        "Do you bite your nails?",
        "Do you pick your nose?",
        "Have you ever peed in a pool?",
        "What is the grossest thing you have done today?",
        "When was the last time you flossed your teeth?",
        "Which would you rather have for dinner, fast-food or Mom home cooking?",
        "Have you ever cried during a movie? If so, which one?",
        "Do you still enjoy Blues Clues?",
        "What is something you wish you were better at?",
        "Have you ever broken something and blamed someone else?",
        "When was the last time you did something nice for someone else?",
        "What is your favorite meal Mom makes?",
        "Have you ever peeked at Christmas presents early?",
        "Have you ever eaten a bug?",
        "Do you pick scabs?",
        "Have you ever passed gas and blamed someone else?"
    ]
